version: 2

models:
  - name: dim_leagues
    description: >
      List of European football leagues identified each identified by a league id.
    columns:
      - name: league_id
        description: "Unique identifier of the league, the primary key."
        meta:
          dimension:
            type: string
            label: "League ID"
        tests:
          - relationships:
              to: ref('dim_teams')
              field: league_id
          - not_null
          - unique
      - name: league_name
        description: "League name."
        meta:
          dimension:
            type: string
            label: "League Name"
        tests:
          - not_null
          - unique

  - name: dim_results
    description: >
      List of matches identified by match_id
      Contains match information from 10 seasons of English Premier League with detailed information on the team names, seasons, half-time and full-time results.
    columns:
      - name: match_id
        description: "Unique identifier for every match, the primary key."
        meta:
          dimension:
            type: string
            label: "Match ID"
        tests:
          - not_null
          - unique
      - name: league_id
        description: "Unique identifier of the league, the foreign key to tracks league."
        meta:
          dimension:
            type: string
            label: "League ID"
        tests:
          - relationships:
              to: ref('dim_leagues')
              field: league_id
          - not_null
      - name: season
        description: "Period or season of the league."
        meta:
          dimension:
            type: string
            label: "Season"
        tests:
          - not_null
      - name: hometeam_id
        description: "Unique identifier for home team."
        meta:
          dimension:
            type: string
            label: "Hometeam ID"
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
          - not_null
      - name: awayteam_id
        description: "Unique identifier for away team."
        meta:
          dimension:
            type: string
            label: "Awayteam ID"
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
          - not_null
      - name: full_time_result
        description: "Full time result - H; Home Wins, D; Draw & A; Away Wins"
        meta:
          dimension:
            type: string
            label: "Fulltime Result"
        tests:
          - accepted_values:
              values: ['H', 'A', 'D']
              severity: warn
          - not_null
      - name: half_time_result
        description: "Half time result - H; Home Wins, D; Draw & A; Away Wins"
        meta:
          dimension:
            type: string
            label: "Halftime Result"
        tests:
          - accepted_values:
              values: ['H', 'A', 'D']
              severity: warn
          - not_null

  - name: dim_teams
    description: >
      List of teams identified team_id and team_name.
    columns:
      - name: team_id
        description: "Unique identifier for every team in the league, the primary key."
        meta:
          dimension:
            type: string
            label: "Team ID"
        tests:
          - not_null
          - unique
      - name: team_name
        description: "Team name."
        meta:
          dimension:
            type: string
            label: "Team Name"
        tests:
          - not_null
      - name: league_id
        description: "Unique identifier of the league, the foreign key to tracks league."
        meta:
          dimension:
            type: string
            label: "League ID"
        tests:
          - not_null
      

  - name: fact_stats
    description: "{{ doc('fact_stats') }}"
    columns:
      - name: league_id
        tests:
          - relationships:
              to: ref('dim_leagues')
              field: league_id
          - not_null
      - name: match_id
        tests:
          - relationships:
              to: ref('dim_results')
              field: match_id
          - not_null
      - name: hometeam_id
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
          - not_null
      - name: awayteam_id
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
          - not_null
    
  - name: fact_league_standings
    description: >
      Table that contains every team wins, draws and loses for every match they played in, home and away.
    columns:
      - name: league_name
        description: "League name."
        meta:
          dimension:
            label: 'League Name'
        tests:
          - not_null
      - name: season
        description: "Period or season of the league."
        meta:
          dimension:
            label: 'Season'
        tests:
          - not_null
      - name: team_name
        description: "Team name."
        meta:
          dimension:
            label: 'Team Name'
          metrics:
            total_matches:
              type: count
              label: "MP"
        tests:
          - not_null
      - name: status
        description: "Home or away status."
        meta:
          dimension:
            label: 'Status'
        tests:
          - not_null
      - name: wins
        description: "Number of wins."
        meta:
          dimension:
            label: 'Wins'
          metrics:
            total_wins:
              type: sum
              label: "W"
        tests:
          - not_null
      - name: draws
        description: "Number of draws."
        meta:
          dimension:
            label: 'Draws'
          metrics:
            total_draws:
              type: sum
              label: "D"
        tests:
          - not_null
      - name: loses
        description: "Number of loses."
        meta:
          dimension:
            label: 'Loses'
          metrics:
            total_loses:
              type: sum
              label: "L"
        tests:
          - not_null
      - name: goals_for
        description: "Number of goals the team has scored."
        meta:
          dimension:
            label: 'Goal Scored'
          metrics:
            total_gf:
              type: sum
              label: "GF"
        tests:
          - not_null
      - name: goals_against
        description: "Number of goals the team has conceded."
        meta:
          dimension:
            label: 'Goals Conceded'
          metrics:
            total_ga:
              type: sum
              label: "GA"
        tests:
          - not_null
      - name: goals_difference
        description: "Number of goals difference between goals scored and conceded."
        meta:
          dimension:
            label: 'Goals Difference'
          metrics:
            total_gd:
              type: sum
              label: "GD"
        tests:
          - not_null
      - name: total_goals_scored
        description: "Number of goals scored."
        meta:
          dimension:
            label: 'Goals Scored'
          metrics:
            total_gs:
              type: sum
              label: "GS"
        tests:
          - not_null
      - name: points
        description: "Points received."
        meta:
          dimension:
            label: 'Points'
          metrics:
            total_points:
              type: sum
              label: "Points"
        tests:
          - not_null

  - name: fact_league_stats
    description: >
      Table that contains every team in-game statistics for every match they played, home and away.
    columns:
      - name: season
        description: "Period or season of the match."
        meta:
          dimension:
            label: 'Season'
        tests:
          - not_null
      - name: match_date
        description: "The date when the match is played."
        meta:
          dimension:
            type: date
            label: 'Match Date'
        tests:
          - not_null
      - name: league_name
        description: "League name."
        meta:
          dimension:
            label: 'League Name'
        tests:
          - not_null
      - name: match_id
        description: "Unique identifier for a match."
        meta:
          dimension:
            label: 'Match ID'
        tests:
          - not_null
      - name: total_goals
        description: "Total goals scored."
        meta:
          dimension:
            label: "Total Goals"
          metrics:
            avg_goals:
              type: average
              labels: "Average Goals"
              round: 2
        tests:
          - not_null
      - name: total_shots
        description: "Total number of shots made."
        meta:
          dimension:
            label: 'Total Shots'
          metrics:
            avg_shots:
              type: average
              labels: "Average Shots"
              round: 2
        tests:
          - not_null
      - name: total_shots_on_target
        description: "Total number of shots on target made."
        meta:
          dimension:
            label: 'Total Shots On Target'
          metrics:
            avg_shots_on_target:
              type: average
              labels: "Average Shots On Target"
              round: 2
        tests:
          - not_null
      - name: total_fouls_commited
        description: "Total number of fouls commited."
        meta:
          dimension:
            label: 'Total Fouls'
          metrics:
            avg_fouls_commited:
              type: average
              labels: "Average Fouls"
        tests:
          - not_null
      - name: total_yellow_cards
        description: "Total number of yellow cards received."
        meta:
          dimension:
            label: 'Total Yellow Cards'
          metrics:
            avg_yellow_cards:
              type: average
              labels: "Average Yellow Cards"
        tests:
          - not_null
      - name: total_red_cards
        description: "Total number of red cards received."
        meta:
          dimension:
            label: 'Total Red Cards'
          metrics:
            avg_red_cards:
              type: average
              labels: "Average Red Cards"
        tests:
          - not_null