version: 2

models:
  - name: dim_leagues
    description: >
      List of unique league identified by leaugue_id.
  - name: dim_matches
    description: >
      List of matches identified by match_id
      Contains match information from 10 seasons of English Premier League with detailed information on the team names, seasons, half-time and full-time results.
  - name: fact_results
    description: "{{ doc('fact_results') }}"
    columns:
      - name: league_id
        tests:
          - not_null
          - relationships:
                to: ref('dim_leagues')
                field: league_id
      - name: match_id
          tests:
            - unique
            - not_null
            - relationships:
                to: ref('dim_matches')
                field: match_id

    
