version: 2

models:
  - name: dim_leagues
    description: >
      List of unique league identified by leaugue_id.
    columns:
      - name: league_id
        tests:
          - relationships:
              to: ref('dim_teams', 'dim_results')
              field: league_id

  - name: dim_results
    description: >
      List of matches identified by match_id
      Contains match information from 10 seasons of English Premier League with detailed information on the team names, seasons, half-time and full-time results.
    columns:
      - name: hometeam_id
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
    columns:
      - name: awayteam_id
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id

  - name: dim_teams
    description: >
      List of teams identified team_id and team_name.

  - name: fact_stats
    description: "{{ doc('fact_stats') }}"
    columns:
      - name: league_id
        tests:
          - relationships:
              to: ref('dim_leagues')
              field: league_id
      - name: match_id
        tests:
          - relationships:
              to: ref('dim_results')
              field: match_id
      - name: hometeam_id
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
      - name: awayteam_id
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
    
    - name: league_standings
      description: >
        Table that contains every team stats for every match they played, home and away.